const fs = require('fs');
let html = fs.readFileSync('pay.html', 'utf8');
html = html.replace(/<h1 class=\"hero-title\">���� Ȯ��<\/h1>/, '<h1 class=\"hero-title\">���ʽ� Ƽ�� (BT) ����</h1>');
html = html.replace(/<p class=\"hero-desc\" id=\"payHeroDesc\">������ QR ����<\/p>/, '<p class=\"hero-desc\" id=\"payHeroDesc\">�������� �߱��� ���� Ƽ���� �޾ƺ�����.</p>');
html = html.replace(/���� ��ũ/g, '��ũ');
html = html.replace(/�����Ϸ���/g, '�����Ϸ���');
html = html.replace(/���� �α��� �� ����/, '���� �α��� �� ����');
html = html.replace(/��Ź ���� Point�� �����˴ϴ�./, '���ʽ� Ƽ��(BT)�� ��� �����˴ϴ�.');
html = html.replace(/<button class=\"btn btn-pay\" id=\"btnPay\" type=\"button\">�����ϱ�<\/button>/, '<button class=\"btn btn-pay\" id=\"btnPay\" type=\"button\" style=\"background:#f59e0b; border-color:#d97706; color:#fff\">Ƽ�� �����ϱ�</button>');
html = html.replace(/?/, '???');
html = html.replace(/���� �Ϸ�!/, '���� �Ϸ�!');
html = html.replace(/<script type=\"module\" src=\"\/assets\/js\/pages\/pay.js\"><\/script>/, '<script type=\"module\" src=\"/assets/js/pages/bt_receive.js\"><\/script>');
html = html.replace(/<div id=\"jackpotResultBox\"[\s\S]*?<\/div>\s*<\/div>\s*<\/div>/, '');
fs.writeFileSync('bt_receive.html', html, 'utf8');

let js = fs.readFileSync('assets/js/pages/pay.js', 'utf8');
js = js.replace(/payMerchantFirebase/g, 'receiveBtQrFirebase');
js = js.replace(/const amountDisp = .*/g, 'const amountDisp = Number(params.get(\"bt\") || 0) + \" BT\";');
js = js.replace(/������ �Ϸ�Ǿ����ϴ�./g, 'BT ������ �Ϸ�Ǿ����ϴ�.');
js = js.replace(/������ �߻��߽��ϴ�./g, '���� �� ������ �߻��߽��ϴ�.');
js = js.replace(/������ ���� ���Դϴ�\.\.\./g, 'Ƽ���� �����ϴ� ���Դϴ�...');
js = js.replace(/const amount = params.get\(\"amount\"\);/, 'const amount = params.get(\"amount\");\n  const bt = params.get(\"bt\");\n  const nonce = params.get(\"nonce\");');
js = js.replace(/receiveBtQrFirebase\(\{([\s\S]*?)\}\)/g, 'receiveBtQrFirebase({ \, bt: Number(new URLSearchParams(window.location.search).get(\"bt\")), nonce: new URLSearchParams(window.location.search).get(\"nonce\") })');
fs.writeFileSync('assets/js/pages/bt_receive.js', js, 'utf8');
console.log('done');
